export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const SUCCESS_CHARACTERS = 'SUCCESS_CHARACTERS';
export const ERROR_CHARACTERS = 'ERROR_CHARACTERS';

export const FETCH_LOCATION = 'FETCH_LOCATION';
export const SUCCESS_LOCATION = 'SUCCESS_LOCATION';
export const ERROR_LOCATION = 'ERROR_LOCATION';

export const FETCH_EPISODES = 'FETCH_EPISODES';
export const SUCCESS_EPISODES = 'SUCCESS_EPISODES';
export const ERROR_EPISODES = 'ERROR_EPISODES';

export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const SUCCESS_CHARACTER = 'SUCCESS_CHARACTER';
export const ERROR_CHARACTER = 'ERROR_CHARACTER';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const SUCCESS_LOCATIONS = 'SUCCESS_LOCATIONS';
export const ERROR_LOCATIONS = 'ERROR_LOCATIONS';

export const FETCH_MULTIPLE_CHARACTERS = 'FETCH_MULTIPLE_CHARACTERS';
export const SUCCESS_MULTIPLE_CHARACTER = 'SUCCESS_MULTIPLE_CHARACTER';
export const ERROR_MULTIPLE_CHARACTER = 'ERROR_MULTIPLE_CHARACTER';

export const FETCH_EPISODE = 'FETCH_EPISODE';
export const SUCCESS_EPISODE = 'SUCCESS_EPISODE';
export const ERROR_EPISODE = 'ERROR_EPISODE';

export const FETCH_MULTIPLE_EPISODES = 'FETCH_MULTIPLE_EPISODES';
export const SUCCESS_MULTIPLE_EPISODES = 'SUCCESS_MULTIPLE_EPISODES';
export const ERROR_MULTIPLE_EPISODES = 'ERROR_MULTIPLE_EPISODES';
